## **1° Module** - TT - Exploratory Data Analysis (EDA)
* April  22°, 2026
#### ESCOM - IPN:

#### *B.S. in Computer Science*
> Miguel Alexander Sanchez Garcia

#### **0° Introduction**

* Data obtained from:

> Sawyer-Lee, R., Gimenez, F., Hoogi, A., & Rubin, D. (2016). Curated Breast Imaging Subset of Digital Database for Screening Mammography (CBIS-DDSM) [Data set]. The Cancer Imaging Archive. https://doi.org/10.7937/K9/TCIA.2016.7O02S9CY

#### **1° Data Load & Cleaning**

**a.** Import the necessaty libraries

In [7]:
import os
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import pydicom
from pathlib import Path
from collections import defaultdict

**b.** Set the paths

In [8]:
# BASE directory for data files
BASE = Path("/Users/alexander_san/TT/Data") 

# CSV filenames
CSV_FILES = {
    "mass_train" : BASE / "mass_case_description_train_set.csv",
    "mass_test"  : BASE / "mass_case_description_test_set.csv",
    "calc_train" : BASE / "calc_case_description_train_set.csv",
    "calc_test"  : BASE / "calc_case_description_test_set.csv",
}

# Check if files exist
print("Paths configured.")
for key, path in CSV_FILES.items():
    status = "OK" if path.exists() else "NOT FOUND"
    print(f"  {key:15s}: {status}  ->  {path.name}")

Paths configured.
  mass_train     : OK  ->  mass_case_description_train_set.csv
  mass_test      : OK  ->  mass_case_description_test_set.csv
  calc_train     : OK  ->  calc_case_description_train_set.csv
  calc_test      : OK  ->  calc_case_description_test_set.csv

**c.** Concatenate the dataframes

In [9]:
def load_cbis_ddsm_csvs(csv_files: dict) -> pd.DataFrame:
    """
    Load and concatenate the CBIS-DDSM CSV files into a single DataFrame.
    Adds 'finding_type' (mass/calc) and 'split' (train/test) columns.

    Parameters
    ----------
    csv_files : dict
        Dictionary mapping dataset keys to file paths.

    Returns
    -------
    pd.DataFrame
        Unified DataFrame with all cases.
    """
    frames = []
    for key, path in csv_files.items():
        split = key.split("_")[1]
        df = pd.read_csv(path)
        df["split"] = split 
        frames.append(df)
        print(f"Loaded {key:15s}: {len(df):>4d} rows  |  {df.shape[1]} columns")

    unified = pd.concat(frames, ignore_index=True)
    print(f"\nTotal rows after concatenation: {len(unified)}")
    return unified


df = load_cbis_ddsm_csvs(CSV_FILES)
df

Loaded mass_train     : 1318 rows  |  15 columns
Loaded mass_test      :  378 rows  |  15 columns
Loaded calc_train     : 1546 rows  |  15 columns
Loaded calc_test      :  326 rows  |  15 columns

Total rows after concatenation: 3568

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path,split,breast density,calc type,calc distribution
0,P_00001,3.0,LEFT,CC,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,train,NaN,NaN,NaN
1,P_00001,3.0,LEFT,MLO,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,train,NaN,NaN,NaN
2,P_00004,3.0,LEFT,CC,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...,train,NaN,NaN,NaN
3,P_00004,3.0,LEFT,MLO,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...,train,NaN,NaN,NaN
4,P_00004,3.0,RIGHT,MLO,1,mass,OVAL,CIRCUMSCRIBED,4,BENIGN,5,Mass-Training_P_00004_RIGHT_MLO/1.3.6.1.4.1.95...,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....,train,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3563,P_02464,NaN,RIGHT,MLO,1,calcification,NaN,NaN,0,MALIGNANT,4,Calc-Test_P_02464_RIGHT_MLO/1.3.6.1.4.1.9590.1...,Calc-Test_P_02464_RIGHT_MLO_1/1.3.6.1.4.1.9590...,Calc-Test_P_02464_RIGHT_MLO_1/1.3.6.1.4.1.9590...,test,2.0,FINE_LINEAR_BRANCHING,CLUSTERED
3564,P_02498,NaN,RIGHT,CC,1,calcification,NaN,NaN,0,BENIGN,3,Calc-Test_P_02498_RIGHT_CC/1.3.6.1.4.1.9590.10...,Calc-Test_P_02498_RIGHT_CC_1/1.3.6.1.4.1.9590....,Calc-Test_P_02498_RIGHT_CC_1/1.3.6.1.4.1.9590....,test,4.0,PUNCTATE,CLUSTERED
3565,P_02498,NaN,RIGHT,MLO,1,calcification,NaN,NaN,0,BENIGN,3,Calc-Test_P_02498_RIGHT_MLO/1.3.6.1.4.1.9590.1...,Calc-Test_P_02498_RIGHT_MLO_1/1.3.6.1.4.1.9590...,Calc-Test_P_02498_RIGHT_MLO_1/1.3.6.1.4.1.9590...,test,4.0,PUNCTATE,CLUSTERED
3566,P_02501,NaN,RIGHT,CC,1,calcification,NaN,NaN,0,MALIGNANT,3,Calc-Test_P_02501_RIGHT_CC/1.3.6.1.4.1.9590.10...,Calc-Test_P_02501_RIGHT_CC_1/1.3.6.1.4.1.9590....,Calc-Test_P_02501_RIGHT_CC_1/1.3.6.1.4.1.9590....,test,3.0,PLEOMORPHIC,CLUSTERED
3567,P_02501,NaN,RIGHT,MLO,1,calcification,NaN,NaN,0,MALIGNANT,3,Calc-Test_P_02501_RIGHT_MLO/1.3.6.1.4.1.9590.1...,Calc-Test_P_02501_RIGHT_MLO_1/1.3.6.1.4.1.9590...,Calc-Test_P_02501_RIGHT_MLO_1/1.3.6.1.4.1.9590...,test,3.0,PLEOMORPHIC,CLUSTERED

c. Clean the pathology feature

In [10]:
df["pathology"] = df["pathology"].str.strip().str.replace("_WITHOUT_CALLBACK", "", regex=False)

label_map = {"BENIGN": 0, "MALIGNANT": 1}
df["label"] = df["pathology"].map(label_map)

df

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path,split,breast density,calc type,calc distribution,label
0,P_00001,3.0,LEFT,CC,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,train,NaN,NaN,NaN,1
1,P_00001,3.0,LEFT,MLO,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,train,NaN,NaN,NaN,1
2,P_00004,3.0,LEFT,CC,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...,train,NaN,NaN,NaN,0
3,P_00004,3.0,LEFT,MLO,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...,train,NaN,NaN,NaN,0
4,P_00004,3.0,RIGHT,MLO,1,mass,OVAL,CIRCUMSCRIBED,4,BENIGN,5,Mass-Training_P_00004_RIGHT_MLO/1.3.6.1.4.1.95...,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....,train,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3563,P_02464,NaN,RIGHT,MLO,1,calcification,NaN,NaN,0,MALIGNANT,4,Calc-Test_P_02464_RIGHT_MLO/1.3.6.1.4.1.9590.1...,Calc-Test_P_02464_RIGHT_MLO_1/1.3.6.1.4.1.9590...,Calc-Test_P_02464_RIGHT_MLO_1/1.3.6.1.4.1.9590...,test,2.0,FINE_LINEAR_BRANCHING,CLUSTERED,1
3564,P_02498,NaN,RIGHT,CC,1,calcification,NaN,NaN,0,BENIGN,3,Calc-Test_P_02498_RIGHT_CC/1.3.6.1.4.1.9590.10...,Calc-Test_P_02498_RIGHT_CC_1/1.3.6.1.4.1.9590....,Calc-Test_P_02498_RIGHT_CC_1/1.3.6.1.4.1.9590....,test,4.0,PUNCTATE,CLUSTERED,0
3565,P_02498,NaN,RIGHT,MLO,1,calcification,NaN,NaN,0,BENIGN,3,Calc-Test_P_02498_RIGHT_MLO/1.3.6.1.4.1.9590.1...,Calc-Test_P_02498_RIGHT_MLO_1/1.3.6.1.4.1.9590...,Calc-Test_P_02498_RIGHT_MLO_1/1.3.6.1.4.1.9590...,test,4.0,PUNCTATE,CLUSTERED,0
3566,P_02501,NaN,RIGHT,CC,1,calcification,NaN,NaN,0,MALIGNANT,3,Calc-Test_P_02501_RIGHT_CC/1.3.6.1.4.1.9590.10...,Calc-Test_P_02501_RIGHT_CC_1/1.3.6.1.4.1.9590....,Calc-Test_P_02501_RIGHT_CC_1/1.3.6.1.4.1.9590....,test,3.0,PLEOMORPHIC,CLUSTERED,1
3567,P_02501,NaN,RIGHT,MLO,1,calcification,NaN,NaN,0,MALIGNANT,3,Calc-Test_P_02501_RIGHT_MLO/1.3.6.1.4.1.9590.1...,Calc-Test_P_02501_RIGHT_MLO_1/1.3.6.1.4.1.9590...,Calc-Test_P_02501_RIGHT_MLO_1/1.3.6.1.4.1.9590...,test,3.0,PLEOMORPHIC,CLUSTERED,1

**d.** Unify the "breast_density" feature

In [11]:
df['breast_density'] = df['breast_density'].combine_first(df['breast density'])

df.drop(columns=["breast density"])

df

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path,split,breast density,calc type,calc distribution,label
0,P_00001,3.0,LEFT,CC,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,train,NaN,NaN,NaN,1
1,P_00001,3.0,LEFT,MLO,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,train,NaN,NaN,NaN,1
2,P_00004,3.0,LEFT,CC,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...,train,NaN,NaN,NaN,0
3,P_00004,3.0,LEFT,MLO,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...,train,NaN,NaN,NaN,0
4,P_00004,3.0,RIGHT,MLO,1,mass,OVAL,CIRCUMSCRIBED,4,BENIGN,5,Mass-Training_P_00004_RIGHT_MLO/1.3.6.1.4.1.95...,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....,train,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3563,P_02464,2.0,RIGHT,MLO,1,calcification,NaN,NaN,0,MALIGNANT,4,Calc-Test_P_02464_RIGHT_MLO/1.3.6.1.4.1.9590.1...,Calc-Test_P_02464_RIGHT_MLO_1/1.3.6.1.4.1.9590...,Calc-Test_P_02464_RIGHT_MLO_1/1.3.6.1.4.1.9590...,test,2.0,FINE_LINEAR_BRANCHING,CLUSTERED,1
3564,P_02498,4.0,RIGHT,CC,1,calcification,NaN,NaN,0,BENIGN,3,Calc-Test_P_02498_RIGHT_CC/1.3.6.1.4.1.9590.10...,Calc-Test_P_02498_RIGHT_CC_1/1.3.6.1.4.1.9590....,Calc-Test_P_02498_RIGHT_CC_1/1.3.6.1.4.1.9590....,test,4.0,PUNCTATE,CLUSTERED,0
3565,P_02498,4.0,RIGHT,MLO,1,calcification,NaN,NaN,0,BENIGN,3,Calc-Test_P_02498_RIGHT_MLO/1.3.6.1.4.1.9590.1...,Calc-Test_P_02498_RIGHT_MLO_1/1.3.6.1.4.1.9590...,Calc-Test_P_02498_RIGHT_MLO_1/1.3.6.1.4.1.9590...,test,4.0,PUNCTATE,CLUSTERED,0
3566,P_02501,3.0,RIGHT,CC,1,calcification,NaN,NaN,0,MALIGNANT,3,Calc-Test_P_02501_RIGHT_CC/1.3.6.1.4.1.9590.10...,Calc-Test_P_02501_RIGHT_CC_1/1.3.6.1.4.1.9590....,Calc-Test_P_02501_RIGHT_CC_1/1.3.6.1.4.1.9590....,test,3.0,PLEOMORPHIC,CLUSTERED,1
3567,P_02501,3.0,RIGHT,MLO,1,calcification,NaN,NaN,0,MALIGNANT,3,Calc-Test_P_02501_RIGHT_MLO/1.3.6.1.4.1.9590.1...,Calc-Test_P_02501_RIGHT_MLO_1/1.3.6.1.4.1.9590...,Calc-Test_P_02501_RIGHT_MLO_1/1.3.6.1.4.1.9590...,test,3.0,PLEOMORPHIC,CLUSTERED,1